// GENERATED by scripts/syncShared.mjs — do not edit directly.
// Edit src/lib/method/validate.ts and run `npm run method:sync`.
//
// Trimmed to the two exports supabase/functions/_shared/method/packs/*.ts
// actually need: PRICING_MENTION (used only inside UNIVERSAL_BANNED) and
// UNIVERSAL_BANNED itself. validateOutput() and its ../vertical/attribution
// dependency stay out of the server build: grading generated output against
// the pack is a client-side UI concern, not a prompt-building one.

/**
 * Pricing, in any form, mentioned in outreach.
 *
 * Not conditional on proof — the doctrine bans this outright ("Names and
 * shapes only. Pricing does not belong in outreach"), whether or not the
 * number behind it is real.
 *
 * Any dollar figure is banned outright rather than only ones next to "per
 * month" — a live generation phrased its invented pricing as "500 to 1,500
 * dollars monthly" with no `$` and no "per", which the first version of this
 * pattern missed entirely. Caught retroactively; broadened so the next
 * rephrasing doesn't get the same free pass.
 */
const PRICING_MENTION = /\$\s?\d[\d,.]*|\b\d[\d,.]*\s*(?:dollars?|usd)\b|\b(?:per|\/|a)\s*(?:month|year|mo|yr)\b|\bmonthly\b|\byearly\b|\bpricing\s+(?:ranges?|starts?|is)\b|\bstarting\s+at\s+\$/i;

/**
 * Patterns every channel bans, merged into each pack. These come from the
 * outreach doctrine in the playbooks and hold regardless of channel.
 */
export const UNIVERSAL_BANNED = [
  {
    id: 'em-dash',
    label: 'Em dash or en dash',
    pattern: /[—–]/,
    because: 'Reads as machine-written to anyone who has seen AI copy. Use a comma, a period or a colon.',
    level: 'hard' as const,
  },
  {
    id: 'hedging',
    label: 'Hedging or supplication',
    pattern: /\b(?:just checking in|hope this finds you well|sorry to bother|worth 30 seconds|hope this isn'?t weird|quick question)\b/i,
    because: 'A sophisticated buyer reads hedging as insecurity and discounts you. Write with a flat, confident spine.',
    level: 'hard' as const,
  },
  {
    id: 'negative-plant',
    label: 'Negated negative',
    pattern: /\b(?:not (?:pitching|selling|trying to sell)|no fluff|not a sales)\b/i,
    because: 'The mind drops the "not" and keeps the noun. Saying "not pitching" makes them think pitch. Rewrite positively.',
    level: 'hard' as const,
  },
  {
    id: 'ai-tell',
    label: 'Generic AI phrasing',
    pattern: /\b(?:in today'?s fast-paced|leverage synergies|I hope this email finds you|delve into|it'?s worth noting that)\b/i,
    because: 'Filler that signals a template. Every sentence should carry something only this sender could write.',
    level: 'soft' as const,
  },
  {
    id: 'emoji',
    label: 'Emoji',
    pattern: /[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u,
    because: 'Wrong register for a senior B2B buyer, and a spam signal in cold email.',
    level: 'soft' as const,
  },
  {
    id: 'pricing-mention',
    label: 'Pricing mentioned',
    pattern: PRICING_MENTION,
    because: 'Names and shapes only — pricing does not belong in outreach, whether or not the figure is real.',
    level: 'hard' as const,
  },
];
