// Keeps supabase/functions/_shared/{method,proof,qualify,vertical}/*.ts in
// sync with their src/lib/ originals.
//
// The edge functions run on Deno, which requires explicit file extensions on
// relative imports; the app's bundler-based src/lib/ imports omit them. That
// one difference is why _shared/ cannot simply import src/lib/ directly, and
// why a hand-maintained copy drifts the moment someone edits src/lib/ and
// forgets the other side. This script is the fix: it is the ONLY thing
// allowed to write into supabase/functions/_shared/{method,proof,qualify,
// vertical}/, by porting each file from its src/lib/ original with three
// mechanical changes — a generated-file header, ".ts" appended to every
// relative import, and LF line endings — and nothing else.
//
// Run with no flags to write the files. Run with --check to verify they
// already match (byte for byte) without writing anything; `npm run build`'s
// prebuild step uses --check so a stale copy fails the build instead of
// silently shipping a server prompt that no longer matches the app's.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC_ROOT = path.join(ROOT, 'src', 'lib');
const DEST_ROOT = path.join(ROOT, 'supabase', 'functions', '_shared');

const header = (relPath) =>
  `// GENERATED by scripts/syncShared.mjs — do not edit directly.\n` +
  `// Edit src/lib/${relPath.split(path.sep).join('/')} and run \`npm run method:sync\`.`;

const toLF = (code) => code.replace(/\r\n/g, '\n');

/**
 * Deno requires explicit extensions on relative imports; src/lib's bundler
 * (Vite/esbuild) does not, so none of the source files carry one. Appends
 * ".ts" to every relative `from '...'` specifier that doesn't already end in
 * one. Matching on `from` rather than the full import statement means a
 * brace-destructured import split across several lines (qualify/score.ts)
 * is handled the same as a one-liner, since the module specifier itself is
 * always on one line regardless of how the imported names are wrapped.
 */
const addTsExtensions = (code) =>
  code.replace(/\bfrom(\s+)(['"])(\.[^'"]*?)\2/g, (full, ws, quote, spec) =>
    /\.[A-Za-z0-9]+$/.test(spec) ? full : `from${ws}${quote}${spec}.ts${quote}`,
  );

/** Trim trailing blank lines, then ensure exactly one trailing newline. */
const trimTrailing = (code) => code.replace(/\s+$/, '\n');

/** A straight port: fixed header, blank line, the whole src file, LF, imports fixed. */
const portVerbatim = (relPath) => {
  const src = toLF(readFileSync(path.join(SRC_ROOT, relPath), 'utf8'));
  const body = trimTrailing(addTsExtensions(src));
  return `${header(relPath)}\n\n${body}`;
};

/**
 * method/validate.ts is special: the edge function only needs the two
 * exports method/packs/linkedin.ts actually imports from it —
 * PRICING_MENTION (used only inside UNIVERSAL_BANNED) and UNIVERSAL_BANNED
 * itself. Porting the whole file would drag in checkAttribution and its
 * ../vertical/attribution import for no behavioural gain, since
 * validateOutput() (the thing that needs it) is a client-side UI concern —
 * grading generated output against the pack — that the server never does.
 *
 * Extracts each block as "the doc comment immediately above the
 * declaration, through the declaration itself", so the extraction tracks
 * whatever comment src/lib/method/validate.ts carries rather than a copy of
 * today's wording.
 */
const portValidateSubset = () => {
  const relPath = 'method/validate.ts';
  const src = toLF(readFileSync(path.join(SRC_ROOT, relPath), 'utf8'));
  const lines = src.split('\n');

  const extractBlock = (startTest, endTest) => {
    const start = lines.findIndex(startTest);
    if (start === -1) throw new Error(`syncShared: could not find the start of a block in ${relPath}`);
    let top = start;
    while (top > 0 && /^\s*(\*|\/\*\*|\/\/)/.test(lines[top - 1])) top--;
    const end = lines.findIndex((l, i) => i >= start && endTest(l));
    if (end === -1) throw new Error(`syncShared: could not find the end of a block in ${relPath}`);
    return lines.slice(top, end + 1).join('\n');
  };

  const pricingBlock = extractBlock(
    (l) => l.startsWith('const PRICING_MENTION'),
    (l) => l.startsWith('const PRICING_MENTION'),
  );
  const bannedBlock = extractBlock(
    (l) => l.startsWith('export const UNIVERSAL_BANNED'),
    (l) => l.trim() === '];',
  );

  const note =
    '//\n' +
    '// Trimmed to the two exports supabase/functions/_shared/method/packs/*.ts\n' +
    '// actually need: PRICING_MENTION (used only inside UNIVERSAL_BANNED) and\n' +
    '// UNIVERSAL_BANNED itself. validateOutput() and its ../vertical/attribution\n' +
    '// dependency stay out of the server build: grading generated output against\n' +
    '// the pack is a client-side UI concern, not a prompt-building one.';

  return `${header(relPath)}\n${note}\n\n${pricingBlock}\n\n${bannedBlock}\n`;
};

/** Every file this script owns, src-relative. validate.ts is handled separately. */
const VERBATIM_FILES = [
  'method/types.ts',
  'method/packs/linkedin.ts',
  'method/compose.ts',
  'proof/types.ts',
  'proof/select.ts',
  'proof/render.ts',
  'qualify/types.ts',
  'qualify/doctrine.ts',
  'qualify/score.ts',
  'qualify/render.ts',
  'vertical/types.ts',
  'vertical/render.ts',
];

const build = () => {
  const out = new Map();
  for (const rel of VERBATIM_FILES) out.set(rel, portVerbatim(rel));
  out.set('method/validate.ts', portValidateSubset());
  return out;
};

const checkMode = process.argv.includes('--check');
const built = build();

if (checkMode) {
  const stale = [];
  for (const [rel, content] of built) {
    const destPath = path.join(DEST_ROOT, rel);
    const current = existsSync(destPath) ? readFileSync(destPath, 'utf8') : null;
    if (current !== content) stale.push(rel);
  }
  if (stale.length) {
    console.error('supabase/functions/_shared is out of sync with src/lib. Run `npm run method:sync`. Stale:');
    for (const rel of stale) console.error(`  - supabase/functions/_shared/${rel}`);
    process.exit(1);
  }
  console.log(`supabase/functions/_shared is in sync (${built.size} files checked).`);
} else {
  for (const [rel, content] of built) {
    writeFileSync(path.join(DEST_ROOT, rel), content, 'utf8');
  }
  console.log(`Synced ${built.size} files into supabase/functions/_shared/.`);
}
